name: Build Artifacts

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  configure:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_BUILD_TYPE=Debug
        -S ${{ github.workspace }}

    - uses: actions/upload-artifact@v4
      with:
        name: build-configure
        path: ${{ steps.strings.outputs.build-output-dir }}

  shared:
    runs-on: ubuntu-latest
    needs: [configure]

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - uses: actions/download-artifact@v4
      with:
        name: build-configure
        path: ${{ steps.strings.outputs.build-output-dir }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Debug --target shared

    - uses: actions/upload-artifact@v4
      with:
        name: build-shared
        path: ${{ steps.strings.outputs.build-output-dir }}

  alpha:
    runs-on: ubuntu-latest
    needs: [shared]

    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - uses: actions/download-artifact@v4
        with:
          name: build-shared
          path: ${{ steps.strings.outputs.build-output-dir }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Debug --target alpha

      - uses: actions/upload-artifact@v4
        with:
          name: build-alpha
          path: ${{ steps.strings.outputs.build-output-dir }}

  beta:
    runs-on: ubuntu-latest
    needs: [shared]

    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          echo VERSION=$VERSION
          echo "build-version=${VERSION}" >> "$GITHUB_OUTPUT"

      - uses: actions/download-artifact@v4
        with:
          name: build-shared
          path: ${{ steps.strings.outputs.build-output-dir }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Debug --target beta

      - uses: actions/upload-artifact@v4
        with:
          name: build-beta
          path: ${{ steps.strings.outputs.build-output-dir }}

  package:
    runs-on: ubuntu-latest
    needs: [shared, alpha, beta]

    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          echo VERSION=$VERSION
          echo "build-version=${VERSION}" >> "$GITHUB_OUTPUT"

      - uses: actions/download-artifact@v4
        with:
          path: ${{ steps.strings.outputs.build-output-dir }}

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCPACK_PACKAGE_VERSION="${{ steps.strings.outputs.build-version }}"
          -S ${{ github.workspace }}

      - name: Package
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Debug --target package

      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.strings.outputs.build-output-dir }}/monorepo-*

