name: Build libshared

on:
  push:
    branches: [ "main", "feature/*" ]
    paths:
      - ".github/workflows/libshared.yml"
      - "libshared"
      - "CMakeLists.txt"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build/libshared" >> "$GITHUB_OUTPUT"
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        [ "$VERSION" == "main" ] && VERSION=latest
        echo VERSION=$VERSION
        echo "build-version=${VERSION}" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -S ${{ github.workspace }}/libshared

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Debug

    - name: Package
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Debug --target package

    - uses: actions/upload-artifact@v4
      with:
        name: monorepo-libshared-${{ steps.strings.outputs.build-version }}
        path: ${{ steps.strings.outputs.build-output-dir }}/*