name: "All: Build and Package"

on:
  push:
    branches: [ "main", "feature/*" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  strings:
    runs-on: ubuntu-latest
    outputs:
      build-dir: ${{ steps.strings.outputs.build-dir }}
      build-version: ${{ steps.strings.outputs.build-version }}
      install-dir: ${{ steps.strings.outputs.install-dir }}
    steps:
      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
          echo "install-dir=${{ github.workspace }}/build/install" >> "$GITHUB_OUTPUT"
          COMMIT_HASH=${{ github.sha }}
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "${{ github.event.repository.default_branch }}" ] && VERSION=latest
          VERSION="$VERSION+sha.${COMMIT_HASH:0:8}"
          echo VERSION=$VERSION
          echo "build-version=${VERSION}" >> "$GITHUB_OUTPUT"

  cache:
    needs: [ strings ]
    runs-on: ubuntu-latest
    outputs:
      project-a-hit: ${{ steps.project-a.outputs.cache-hit }}
      project-a-key: ${{ steps.project-a.outputs.cache-primary-key }}
      project-b-hit: ${{ steps.project-b.outputs.cache-hit }}
      project-b-key: ${{ steps.project-b.outputs.cache-primary-key }}
      project-c-hit: ${{ steps.project-c.outputs.cache-hit }}
      project-c-key: ${{ steps.project-c.outputs.cache-primary-key }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/cache/restore@v4
        id: project-a
        with:
          lookup-only: true
          key: ${{ runner.os }}-project-a-${{ hashFiles('project-a/**') }}
          path: |
            ${{ needs.strings.outputs.build-dir }}/project-a/project-a-*

      - uses: actions/cache/restore@v4
        id: project-b
        with:
          lookup-only: true
          key: ${{ runner.os }}-project-b-${{ hashFiles('project-a/**', 'project-b/**') }}
          path: |
            ${{ needs.strings.outputs.build-dir }}/project-b/project-b-*

      - uses: actions/cache/restore@v4
        id: project-c
        with:
          lookup-only: true
          key: ${{ runner.os }}-project-c-${{ hashFiles('project-a/**', 'project-c/**') }}
          path: |
            ${{ needs.strings.outputs.build-dir }}/project-c/project-c-*


  project-a:
    needs: [ strings, cache ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/cache@v4
        id: cache
        with:
          key: ${{ needs.cache.outputs.project-a-key }}
          path: |
            ${{ needs.strings.outputs.build-dir }}/project-a/project-a-*

      - uses: lukka/get-cmake@latest
        if: steps.cache.outputs.cache-hit != 'true'

      - uses: lukka/run-vcpkg@v11.5
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Configure CMake
        if: steps.cache.outputs.cache-hit != 'true'
        run: cmake --preset project-a

      - name: Build
        if: steps.cache.outputs.cache-hit != 'true'
        run: cmake --build --preset project-a/all

      - name: Test
        if: steps.cache.outputs.cache-hit != 'true'
        run: ctest --preset project-a

      - name: Package
        if: steps.cache.outputs.cache-hit != 'true'
        run: cpack --preset project-a -R "${{ needs.strings.outputs.build-version }}"

      - uses: actions/upload-artifact@v4
        with:
          name: project-a-${{ needs.strings.outputs.build-version }}
          path: ${{ needs.strings.outputs.build-dir }}/project-a/project-a-*
          if-no-files-found: error


  project-b:
    needs: [ strings, cache, project-a ]
    runs-on: ubuntu-latest
    if: needs.cache.outputs.project-b-hit != 'true'
    steps:
      - uses: actions/checkout@v5

      - uses: actions/cache/restore@v4
        with:
          key: ${{ needs.cache.outputs.project-a-key }}
          fail-on-cache-miss: true
          path: |
            ${{ needs.strings.outputs.build-dir }}/project-a/project-a-*

      - uses: lukka/get-cmake@latest

      - uses: lukka/run-vcpkg@v11.5

      - name: Install Dependency
        run: >
          sh ${{ needs.strings.outputs.build-dir }}/project-a/project-a-*.sh
          --skip-license
          --include-subdir
          --prefix=${{ needs.strings.outputs.install-dir }}

      - name: Configure CMake
        run: cmake --preset project-b

      - name: Build
        run: cmake --build --preset project-b/all

      - name: Test
        run: ctest --preset project-b

      - name: Package
        run: cpack --preset project-b -R "${{ needs.strings.outputs.build-version }}"

      - uses: actions/cache/save@v4
        with:
          key: ${{ needs.cache.outputs.project-b-key }}
          path: |
            ${{ needs.strings.outputs.build-dir }}/project-b/project-b-*

      - uses: actions/upload-artifact@v4
        with:
          name: project-b-${{ needs.strings.outputs.build-version }}
          path: ${{ needs.strings.outputs.build-dir }}/project-b/project-b-*
          if-no-files-found: error


  project-c:
    needs: [ strings, project-a ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/cache@v4
        id: cache
        with:
          key: ${{ runner.os }}-project-a-${{ hashFiles('project-a/**', 'project-c/**') }}
          path: |
            ${{ needs.strings.outputs.build-dir }}/project-c/project-c-*

      - uses: lukka/get-cmake@latest
        if: steps.cache.outputs.cache-hit != 'true'

      - uses: lukka/run-vcpkg@v11.5
        if: steps.cache.outputs.cache-hit != 'true'

      - uses: actions/download-artifact@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          pattern: project-a-*
          path: ${{ needs.strings.outputs.build-dir }}

      - name: Install Dependency
        if: steps.cache.outputs.cache-hit != 'true'
        run: >
          sh ${{ needs.strings.outputs.build-dir }}/project-a-*/project-a-*.sh
          --skip-license
          --include-subdir
          --prefix=${{ needs.strings.outputs.install-dir }}

      - name: Configure CMake
        if: steps.cache.outputs.cache-hit != 'true'
        run: cmake --preset project-c

      - name: Build
        if: steps.cache.outputs.cache-hit != 'true'
        run: cmake --build --preset project-c/all

      - name: Test
        if: steps.cache.outputs.cache-hit != 'true'
        run: ctest --preset project-c

      - name: Package
        if: steps.cache.outputs.cache-hit != 'true'
        run: cpack --preset project-c -R "${{ needs.strings.outputs.build-version }}"

      - uses: actions/upload-artifact@v4
        with:
          name: project-c-${{ needs.strings.outputs.build-version }}
          path: ${{ needs.strings.outputs.build-dir }}/project-c/project-c-*
          if-no-files-found: error

