name: "Project B: Build and Package"

on:
  push:
    branches: [ "main", "feature/*" ]
    paths:
      - project-b/**
      - .github/workflows/project-b.yml
  pull_request:
    branches: [ "main" ]
    paths:
      - project-b/**
      - .github/workflows/project-b.yml

env:
  project_name: project-b
  build_type: Debug

jobs:
  configure:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: project-a.yml
        workflow_conclusion: success
        branch: main
        event: push
        name: package-.*
        # Optional, name is treated as a regular expression if set true
        name_is_regexp: true
        # Optional, a directory where to extract artifact(s), defaults to the current directory
        path: build

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_BUILD_TYPE=${{env.build_type}}
        -S ${{ github.workspace }}/${{env.project_name}}

    - uses: actions/upload-artifact@v4
      with:
        name: build-configure
        path: ${{ steps.strings.outputs.build-output-dir }}

  gamma:
    runs-on: ubuntu-latest
    needs: [configure]

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - uses: actions/download-artifact@v4
      with:
        name: build-configure
        path: ${{ steps.strings.outputs.build-output-dir }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{env.build_type}} --target gamma

    - uses: actions/upload-artifact@v4
      with:
        name: build-gamma
        path: ${{ steps.strings.outputs.build-output-dir }}

  package:
    runs-on: ubuntu-latest
    needs: [gamma]

    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          echo VERSION=$VERSION
          echo "build-version=${VERSION}" >> "$GITHUB_OUTPUT"

      - uses: actions/download-artifact@v4
        with:
          path: ${{ steps.strings.outputs.build-output-dir }}

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCPACK_PACKAGE_VERSION="${{ steps.strings.outputs.build-version }}"
          -S ${{ github.workspace }}/${{env.project_name}}

      - name: Package
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{env.build_type}} --target package

      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.strings.outputs.build-output-dir }}/${{env.project_name}}-*

