name: "Project A: Build and Package"

on:
  push:
    branches: [ "main", "feature/*" ]
    paths:
      - project-a/**
      - .github/workflows/project-a.yml
  pull_request:
    branches: [ "main" ]
    paths:
      - project-a/**
      - .github/workflows/project-a.yml

env:
  project_name: project-a
  build_type: Debug

jobs:
  configure:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        [ "$VERSION" == "main" ] && VERSION=latest
        echo VERSION=$VERSION
        echo "build-version=${VERSION}" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_BUILD_TYPE=${{env.build_type}}
        -DCPACK_PACKAGE_VERSION="${{ steps.strings.outputs.build-version }}"
        -S ${{ github.workspace }}/${{env.project_name}}

    - uses: actions/upload-artifact@v4
      with:
        name: configure
        path: ${{ steps.strings.outputs.build-output-dir }}

  libraries:
    runs-on: ubuntu-latest
    needs: [configure]
    strategy:
      fail-fast: true

      matrix:
        target:
          - shared
          - special

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - uses: actions/download-artifact@v4
      with:
        name: configure
        path: ${{ steps.strings.outputs.build-output-dir }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ env.build_type }} --target ${{ matrix.target }}

    - uses: actions/upload-artifact@v4
      with:
        name: libraries-${{ matrix.target }}
        path: ${{ steps.strings.outputs.build-output-dir }}

  applications:
    runs-on: ubuntu-latest
    needs: [libraries]
    strategy:
      fail-fast: true
      matrix:
        target:
          - alpha
          - beta
    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - uses: actions/download-artifact@v4
        with:
          name: libraries-*
          path: ${{ steps.strings.outputs.build-output-dir }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{env.build_type}} --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v4
        with:
          name: applications-${{ matrix.target }}
          path: ${{ steps.strings.outputs.build-output-dir }}

  package:
    runs-on: ubuntu-latest
    needs: [libraries, applications]

    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          echo VERSION=$VERSION
          echo "build-version=${VERSION}" >> "$GITHUB_OUTPUT"

      - uses: actions/download-artifact@v4
        with:
          name: applications-*
          path: ${{ steps.strings.outputs.build-output-dir }}

      - name: Package
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{env.build_type}} --target package

      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.strings.outputs.build-output-dir }}/${{env.project_name}}-*

